export const FeaturedProducts = [
  {
    name: 'Transplanter with Plastic Sleeve',
    category: 'Plant accessories',
    img: '/products/img-1.jpg',
    price: '18.90',
    info: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius, odit debitis consequatur, vel ipsam voluptatem sed asperiores officiis obcaecati aspernatur quisquam quidem eos quaerat at!',
    inStock: true,
    freeShipping: false,
  },
  {
    name: 'Single Prong Weeder',
    category: 'Plant accessories',
    img: '/products/img-5.jpg',
    price: '11.90',
    info: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius, odit debitis consequatur, vel ipsam voluptatem sed asperiores officiis obcaecati aspernatur quisquam quidem eos quaerat at!',
    inStock: true,
    freeShipping: true,
  },
  {
    name: 'Trowel with Plastic Sleeve',
    category: 'Plant accessories',
    img: '/products/img-2.jpg',
    price: '20.90',
    info: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius, odit debitis consequatur, vel ipsam voluptatem sed asperiores officiis obcaecati aspernatur quisquam quidem eos quaerat at!',
    inStock: true,
    freeShipping: true,
  },
  {
    name: 'Bypass Secateur',
    category: 'Plant accessories',
    img: '/products/img-3.jpg',
    price: '25.90',
    info: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius, odit debitis consequatur, vel ipsam voluptatem sed asperiores officiis obcaecati aspernatur quisquam quidem eos quaerat at!',
    inStock: true,
    freeShipping: true,
  },
  {
    name: 'Straight Blade Scissor',
    category: 'Plant accessories',
    img: '/products/img-4.jpg',
    price: '18.90',
    info: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius, odit debitis consequatur, vel ipsam voluptatem sed asperiores officiis obcaecati aspernatur quisquam quidem eos quaerat at!',
    inStock: true,
    freeShipping: true,
  },
  {
    name: 'Birdnest Japanese',
    category: 'Plant accessories',
    img: '/products/featured-img-8.jpg',
    price: '55.90',
    info: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius, odit debitis consequatur, vel ipsam voluptatem sed asperiores officiis obcaecati aspernatur quisquam quidem eos quaerat at!',
    inStock: true,
    freeShipping: true,
  },
];

export const products = [
  {
    name: 'Transplanter with Plastic Sleeve',
    category: 'Plant accessories',
    img: '/products/img-1.jpg',
    price: '18.90',
    info: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius, odit debitis consequatur, vel ipsam voluptatem sed asperiores officiis obcaecati aspernatur quisquam quidem eos quaerat at!',
    inStock: true,
    featured: false,
    featured: false,
    freeShipping: false,
  },
  {
    name: 'Single Prong Weeder',
    category: 'Plant accessories',
    img: '/products/img-5.jpg',
    price: '11.90',
    info: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius, odit debitis consequatur, vel ipsam voluptatem sed asperiores officiis obcaecati aspernatur quisquam quidem eos quaerat at!',
    inStock: true,
    featured: false,
    freeShipping: true,
  },
  {
    name: 'Trowel with Plastic Sleeve',
    category: 'Plant accessories',
    img: '/products/img-2.jpg',
    price: '20.90',
    info: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius, odit debitis consequatur, vel ipsam voluptatem sed asperiores officiis obcaecati aspernatur quisquam quidem eos quaerat at!',
    inStock: true,
    featured: false,
    freeShipping: true,
  },
  {
    name: 'Bypass Secateur',
    category: 'Plant accessories',
    img: '/products/img-3.jpg',
    price: '25.90',
    info: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius, odit debitis consequatur, vel ipsam voluptatem sed asperiores officiis obcaecati aspernatur quisquam quidem eos quaerat at!',
    inStock: true,
    featured: false,
    freeShipping: true,
  },
  {
    name: 'Straight Blade Scissor',
    category: 'Plant accessories',
    img: '/products/img-4.jpg',
    price: '18.90',
    info: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius, odit debitis consequatur, vel ipsam voluptatem sed asperiores officiis obcaecati aspernatur quisquam quidem eos quaerat at!',
    inStock: true,
    featured: false,
    freeShipping: true,
  },
  {
    name: 'Birdnest Japanese',
    category: 'Air purifying ',
    img: '/products/featured-img-8.jpg',
    price: '55.90',
    info: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius, odit debitis consequatur, vel ipsam voluptatem sed asperiores officiis obcaecati aspernatur quisquam quidem eos quaerat at!',
    inStock: true,
    featured: false,
    freeShipping: true,
  },
  {
    name: 'Hoya Obovatum',
    category: 'Indoor Plants',
    img: '/products/featured-img-5.jpg',
    price: '49.90',
    info: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius, odit debitis consequatur, vel ipsam voluptatem sed asperiores officiis obcaecati aspernatur quisquam quidem eos quaerat at!',
    inStock: true,
    featured: false,
    freeShipping: true,
  },
  {
    name: 'Monstera Deliciosa',
    category: 'Air purifying',
    img: '/products/featured-img-14.jpg',
    price: '169.90',
    info: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius, odit debitis consequatur, vel ipsam voluptatem sed asperiores officiis obcaecati aspernatur quisquam quidem eos quaerat at!',
    inStock: true,
    featured: false,
    freeShipping: true,
  },
  {
    name: 'Zz Plants',
    category: 'Herbs seeds',
    img: '/products/featured-img-16.jpg',
    price: '99.90',
    info: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius, odit debitis consequatur, vel ipsam voluptatem sed asperiores officiis obcaecati aspernatur quisquam quidem eos quaerat at!',
    inStock: true,
    featured: false,
    freeShipping: true,
  },
  {
    name: 'Bird of Paradise',
    category: 'Ceramic pots',
    img: '/products/featured-img-4.jpg',
    price: '199.90',
    info: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius, odit debitis consequatur, vel ipsam voluptatem sed asperiores officiis obcaecati aspernatur quisquam quidem eos quaerat at!',
    inStock: true,
    featured: false,
    freeShipping: true,
  },
  {
    name: 'Calathea Beauty Star',
    category: 'Herbs seeds',
    img: '/products/featured-img-7.jpg',
    price: '79.90',
    info: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius, odit debitis consequatur, vel ipsam voluptatem sed asperiores officiis obcaecati aspernatur quisquam quidem eos quaerat at!',
    inStock: true,
    featured: false,
    freeShipping: true,
  },
  {
    name: 'Dracaena Lisa',
    category: 'Air purifying',
    img: '/products/featured-img-7.jpg',
    price: '114.90',
    info: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius, odit debitis consequatur, vel ipsam voluptatem sed asperiores officiis obcaecati aspernatur quisquam quidem eos quaerat at!',
    inStock: true,
    featured: false,
    freeShipping: true,
  },
  {
    name: 'Spathiphyllum',
    category: 'Indoor Plants',
    img: '/products/featured-img-15.jpg',
    price: '94.90',
    info: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius, odit debitis consequatur, vel ipsam voluptatem sed asperiores officiis obcaecati aspernatur quisquam quidem eos quaerat at!',
    inStock: true,
    featured: false,
    freeShipping: true,
  },
  {
    name: 'Peperomia Lemon Lime',
    category: 'Low maintenance ',
    img: '/products/featured-img-12.jpg',
    price: '32.90',
    info: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius, odit debitis consequatur, vel ipsam voluptatem sed asperiores officiis obcaecati aspernatur quisquam quidem eos quaerat at!',
    inStock: true,
    featured: false,
    freeShipping: true,
  },
  {
    name: 'Pachira Braid',
    category: 'Ceramic pots',
    img: '/products/featured-img-13.jpg',
    price: '74.90',
    info: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius, odit debitis consequatur, vel ipsam voluptatem sed asperiores officiis obcaecati aspernatur quisquam quidem eos quaerat at!',
    inStock: true,
    featured: false,
    freeShipping: true,
  },
  {
    name: 'Aralia Ming',
    category: 'Air purifying',
    img: '/products/featured-img-19.jpg',
    price: '284.90',
    info: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius, odit debitis consequatur, vel ipsam voluptatem sed asperiores officiis obcaecati aspernatur quisquam quidem eos quaerat at!',
    inStock: true,
    featured: false,
    freeShipping: true,
  },
  {
    name: 'Calathea Rufibarba',
    category: 'Herbs seeds ',
    img: '/products/featured-img-18.jpg',
    price: '109.90',
    info: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius, odit debitis consequatur, vel ipsam voluptatem sed asperiores officiis obcaecati aspernatur quisquam quidem eos quaerat at!',
    inStock: true,
    featured: false,
    freeShipping: true,
  },
  {
    name: 'Pilea Peperomioides',
    category: 'Low maintenance ',
    img: '/products/featured-img-5.jpg',
    price: '24.00',
    info: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius, odit debitis consequatur, vel ipsam voluptatem sed asperiores officiis obcaecati aspernatur quisquam quidem eos quaerat at!',
    inStock: true,
    featured: false,
    freeShipping: true,
  },
  {
    name: 'Euphorbia Ingens',
    category: 'Ceramic pots',
    img: '/products/featured-img-10.jpg',
    price: '104.00',
    info: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius, odit debitis consequatur, vel ipsam voluptatem sed asperiores officiis obcaecati aspernatur quisquam quidem eos quaerat at!',
    inStock: true,
    featured: false,
    freeShipping: true,
  },
  {
    name: 'Ficus Decora Cabernet',
    category: 'Air purifying ',
    img: '/products/featured-img-6.jpg',
    price: '124.90',
    info: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius, odit debitis consequatur, vel ipsam voluptatem sed asperiores officiis obcaecati aspernatur quisquam quidem eos quaerat at!',
    inStock: true,
    featured: false,
    freeShipping: true,
  },
  {
    name: 'Ficus Decora Burgundy',
    category: 'Herbs seeds',
    img: '/products/featured-img-2.jpg',
    price: '89.90',
    info: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius, odit debitis consequatur, vel ipsam voluptatem sed asperiores officiis obcaecati aspernatur quisquam quidem eos quaerat at!',
    inStock: true,
    featured: false,
    freeShipping: true,
  },
  {
    name: 'Sansevieria Golden Flame',
    category: 'Ceramic pots',
    img: '/products/featured-img-3.jpg',
    price: '49.90',
    info: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius, odit debitis consequatur, vel ipsam voluptatem sed asperiores officiis obcaecati aspernatur quisquam quidem eos quaerat at!',
    inStock: true,
    featured: false,
    freeShipping: true,
  },
  {
    name: 'Golden Pothos Pole',
    category: 'Air purifying',
    img: '/products/featured-img-9.jpg',
    price: '74.90',
    info: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius, odit debitis consequatur, vel ipsam voluptatem sed asperiores officiis obcaecati aspernatur quisquam quidem eos quaerat at!',
    inStock: true,
    featured: false,
    freeShipping: true,
  },
  {
    name: 'Sansevieria Laurentii',
    category: 'Indoor Plants',
    img: '/products/featured-img-1.jpg',
    price: '79.90',
    info: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius, odit debitis consequatur, vel ipsam voluptatem sed asperiores officiis obcaecati aspernatur quisquam quidem eos quaerat at!',
    inStock: true,
    featured: false,
    freeShipping: true,
  },
  {
    name: 'Alocasia Regal Shield',
    category: 'Air purifying',
    img: '/products/featured-img-17.jpg',
    price: '204.90',
    info: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius, odit debitis consequatur, vel ipsam voluptatem sed asperiores officiis obcaecati aspernatur quisquam quidem eos quaerat at!',
    inStock: true,
    featured: false,
    freeShipping: true,
  },
];
